naked_fields warning (issue #37)
Ovid/moosex-extreme pull request #38
Opened 2022-06-26 15:40 UTC by tobyink

I'm pretty sure this is a comprehensive condition for checking that a field is unsettable in any way.

```perl
    if ( !exists $opt_for{accessor}
    and  !exists $opt_for{writer}
    and  !exists $opt_for{default}
    and  !exists $opt_for{builder}
    and  !defined $opt_for{init_arg}
    and  ( $opt_for{is} // 'ro' ) eq 'ro' ) {
```

I don't especially like the hard-coding of the call level; it could break down if a MooseX::Extended::Custom module wraps `field` or `param`. Can you think of a better solution for that?

2022-06-26 16:04 UTC, tobyink commented
Annoyingly `warnings::enabled_at_level` only works for Perl 5.28+

2022-06-27 09:00 UTC, Ovid requested changes
I like what I see! Here are my first thoughts.

2022-06-29 14:09 UTC, tobyink commented on lib/MooseX/Extended/Core.pm
> +    if (    not exists $opt_for{accessor}
Accessors can be used as writers, so if the attribute has an accessor, it's not naked.

2022-06-29 14:10 UTC, tobyink commented on lib/MooseX/Extended/Core.pm
> +        and ( not defined $opt_for{is} or $opt_for{is} eq 'ro' ) )
Good point.

2022-06-30 06:25 UTC, Ovid commented on lib/MooseX/Extended/Core.pm
> +    if (    not exists $opt_for{accessor}
I think I wasn't clear and this is still confusing to me. We don't define any kind of "accessor" option for `param` or `field` and [according to the docs](https://metacpan.org/pod/Moose::Meta::Attribute), I don't see any such option available for `has`. Have I misunderstood something?

Also, to me, the terms "accessor" and "mutator" are synonumous with "reader" and "writer", respectively, though I realize others use terms differently. Can you show me a working example of what you mean?

2022-07-01 15:40 UTC, tobyink commented on lib/MooseX/Extended/Core.pm
> +    if (    not exists $opt_for{accessor}
The Moose MOP pod is a twisty maze. `accessor` is defined in [Class::MOP::Attribute](https://metacpan.org/pod/Class::MOP::Attribute).

This works in Moose, for example:

```perl
has attr => (
  is => 'bare',
  reader => 'get_attr',
  writer => 'set_attr',
  accessor => 'getset_attr',
);
```

`get_attr` will be a reader method, which can only be used to read the attribute's value. `set_attr` will be a writer method, which can only be used to set the attribute's value. `getset_attr` will be an accessor method, which behaves as a reader if called with no arguments and a writer if called with an argument.

The `reader`, `writer` and `accessor` options for `has` are also mentioned in [perldoc Moose](https://metacpan.org/pod/Moose#has-+$name-=%3E-%25options) but only very briefly, and the difference between them isn't explained.

2022-07-01 15:58 UTC, Ovid commented on lib/MooseX/Extended/Core.pm
> +        my $call_level = 2;    # XXX: better way than hard-coding?
For now, this seems like such an unlikely edge case, why not just document it and punt on the issue?

2022-07-02 22:38 UTC, tobyink commented
Better now?

2022-07-03 10:38 UTC, Ovid commented
I've gone ahead and merged this. Thank you!

2022-07-03 10:38 UTC, closed without merging